package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdditionalCandidates generated by hbm2java
 */
@Entity
@Table(name = "additional_candidates", catalog = "management_resource_human_database")
public class AdditionalCandidates implements java.io.Serializable {

	private Integer idAdditionalCandidates;
	private Boolean cv;
	private Boolean ldm;
	private Integer durationTraineeship;
	private Integer durationExpPro;
	private String diploma;
	private String specialty;
	private String departement;
	private String note;
	private String meetingDate;
	private String post;
	private Set<Candidates> candidateses = new HashSet<Candidates>(0);

	public AdditionalCandidates() {
	}

	public AdditionalCandidates(Boolean cv, Boolean ldm,
			Integer durationTraineeship, Integer durationExpPro,
			String diploma, String specialty, String departement, String note,
			String meetingDate, String post, Set<Candidates> candidateses) {
		this.cv = cv;
		this.ldm = ldm;
		this.durationTraineeship = durationTraineeship;
		this.durationExpPro = durationExpPro;
		this.diploma = diploma;
		this.specialty = specialty;
		this.departement = departement;
		this.note = note;
		this.meetingDate = meetingDate;
		this.post = post;
		this.candidateses = candidateses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_additional_candidates", unique = true, nullable = false)
	public Integer getIdAdditionalCandidates() {
		return this.idAdditionalCandidates;
	}

	public void setIdAdditionalCandidates(Integer idAdditionalCandidates) {
		this.idAdditionalCandidates = idAdditionalCandidates;
	}

	@Column(name = "cv")
	public Boolean getCv() {
		return this.cv;
	}

	public void setCv(Boolean cv) {
		this.cv = cv;
	}

	@Column(name = "ldm")
	public Boolean getLdm() {
		return this.ldm;
	}

	public void setLdm(Boolean ldm) {
		this.ldm = ldm;
	}

	@Column(name = "duration_traineeship")
	public Integer getDurationTraineeship() {
		return this.durationTraineeship;
	}

	public void setDurationTraineeship(Integer durationTraineeship) {
		this.durationTraineeship = durationTraineeship;
	}

	@Column(name = "duration_exp_pro")
	public Integer getDurationExpPro() {
		return this.durationExpPro;
	}

	public void setDurationExpPro(Integer durationExpPro) {
		this.durationExpPro = durationExpPro;
	}

	@Column(name = "diploma", length = 10)
	public String getDiploma() {
		return this.diploma;
	}

	public void setDiploma(String diploma) {
		this.diploma = diploma;
	}

	@Column(name = "specialty", length = 100)
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@Column(name = "departement", length = 25)
	public String getDepartement() {
		return this.departement;
	}

	public void setDepartement(String departement) {
		this.departement = departement;
	}

	@Column(name = "note", length = 500)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "meeting_date", length = 20)
	public String getMeetingDate() {
		return this.meetingDate;
	}

	public void setMeetingDate(String meetingDate) {
		this.meetingDate = meetingDate;
	}

	@Column(name = "post", length = 25)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "additionalCandidates")
	public Set<Candidates> getCandidateses() {
		return this.candidateses;
	}

	public void setCandidateses(Set<Candidates> candidateses) {
		this.candidateses = candidateses;
	}

}
