package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Candidates generated by hbm2java
 */
@Entity
@Table(name = "candidates", catalog = "management_resource_human_database")
public class Candidates implements java.io.Serializable {

	private String email;
	private AdditionalCandidates additionalCandidates;
	private EmailsTrackings emailsTrackings;
	private Date dateAdd;
	private Integer cin;
	private Date cinIssued;
	private String firstName;
	private String lastName;
	private String sexe;
	private String address;
	private Date birthday;
	private String nationality;
	private String tel;
	private String passportNumber;
	private String familySituation;
	private Integer childNumber;
	private String etatCandidature;
	private Set<CtpFolders> ctpFolderses = new HashSet<CtpFolders>(0);

	public Candidates() {
	}

	public Candidates(String email) {
		this.email = email;
	}

	public Candidates(String email, AdditionalCandidates additionalCandidates,
			EmailsTrackings emailsTrackings, Date dateAdd, Integer cin,
			Date cinIssued, String firstName, String lastName, String sexe,
			String address, Date birthday, String nationality, String tel,
			String passportNumber, String familySituation, Integer childNumber,
			String etatCandidature, Set<CtpFolders> ctpFolderses) {
		this.email = email;
		this.additionalCandidates = additionalCandidates;
		this.emailsTrackings = emailsTrackings;
		this.dateAdd = dateAdd;
		this.cin = cin;
		this.cinIssued = cinIssued;
		this.firstName = firstName;
		this.lastName = lastName;
		this.sexe = sexe;
		this.address = address;
		this.birthday = birthday;
		this.nationality = nationality;
		this.tel = tel;
		this.passportNumber = passportNumber;
		this.familySituation = familySituation;
		this.childNumber = childNumber;
		this.etatCandidature = etatCandidature;
		this.ctpFolderses = ctpFolderses;
	}

	@Id
	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_additional_candidates")
	public AdditionalCandidates getAdditionalCandidates() {
		return this.additionalCandidates;
	}

	public void setAdditionalCandidates(
			AdditionalCandidates additionalCandidates) {
		this.additionalCandidates = additionalCandidates;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_emails_trackings")
	public EmailsTrackings getEmailsTrackings() {
		return this.emailsTrackings;
	}

	public void setEmailsTrackings(EmailsTrackings emailsTrackings) {
		this.emailsTrackings = emailsTrackings;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_add", length = 10)
	public Date getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Date dateAdd) {
		this.dateAdd = dateAdd;
	}

	@Column(name = "cin")
	public Integer getCin() {
		return this.cin;
	}

	public void setCin(Integer cin) {
		this.cin = cin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cin_issued", length = 10)
	public Date getCinIssued() {
		return this.cinIssued;
	}

	public void setCinIssued(Date cinIssued) {
		this.cinIssued = cinIssued;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "sexe", length = 1)
	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	@Column(name = "address", length = 25)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "nationality", length = 50)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "tel", length = 100)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "passport_number", length = 12)
	public String getPassportNumber() {
		return this.passportNumber;
	}

	public void setPassportNumber(String passportNumber) {
		this.passportNumber = passportNumber;
	}

	@Column(name = "family_situation", length = 15)
	public String getFamilySituation() {
		return this.familySituation;
	}

	public void setFamilySituation(String familySituation) {
		this.familySituation = familySituation;
	}

	@Column(name = "child_number")
	public Integer getChildNumber() {
		return this.childNumber;
	}

	public void setChildNumber(Integer childNumber) {
		this.childNumber = childNumber;
	}

	@Column(name = "etat_candidature", length = 100)
	public String getEtatCandidature() {
		return this.etatCandidature;
	}

	public void setEtatCandidature(String etatCandidature) {
		this.etatCandidature = etatCandidature;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "candidates")
	public Set<CtpFolders> getCtpFolderses() {
		return this.ctpFolderses;
	}

	public void setCtpFolderses(Set<CtpFolders> ctpFolderses) {
		this.ctpFolderses = ctpFolderses;
	}

}
