package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContenuValidac generated by hbm2java
 */
@Entity
@Table(name = "contenu_validac", catalog = "management_resource_human_database")
public class ContenuValidac implements java.io.Serializable {

	private Integer idContenuValidac;
	private Validacs validacs;
	private String objectif;
	private String initiale;
	private String pratique;
	private String perfectione;
	private String demontre;
	private String acteur;

	public ContenuValidac() {
	}

	public ContenuValidac(Validacs validacs, String objectif, String initiale,
			String pratique, String perfectione, String demontre, String acteur) {
		this.validacs = validacs;
		this.objectif = objectif;
		this.initiale = initiale;
		this.pratique = pratique;
		this.perfectione = perfectione;
		this.demontre = demontre;
		this.acteur = acteur;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_contenu_validac", unique = true, nullable = false)
	public Integer getIdContenuValidac() {
		return this.idContenuValidac;
	}

	public void setIdContenuValidac(Integer idContenuValidac) {
		this.idContenuValidac = idContenuValidac;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_validac")
	public Validacs getValidacs() {
		return this.validacs;
	}

	public void setValidacs(Validacs validacs) {
		this.validacs = validacs;
	}

	@Column(name = "objectif", length = 11)
	public String getObjectif() {
		return this.objectif;
	}

	public void setObjectif(String objectif) {
		this.objectif = objectif;
	}

	@Column(name = "initiale", length = 11)
	public String getInitiale() {
		return this.initiale;
	}

	public void setInitiale(String initiale) {
		this.initiale = initiale;
	}

	@Column(name = "pratique", length = 11)
	public String getPratique() {
		return this.pratique;
	}

	public void setPratique(String pratique) {
		this.pratique = pratique;
	}

	@Column(name = "perfectione", length = 11)
	public String getPerfectione() {
		return this.perfectione;
	}

	public void setPerfectione(String perfectione) {
		this.perfectione = perfectione;
	}

	@Column(name = "demontre", length = 11)
	public String getDemontre() {
		return this.demontre;
	}

	public void setDemontre(String demontre) {
		this.demontre = demontre;
	}

	@Column(name = "acteur", length = 50)
	public String getActeur() {
		return this.acteur;
	}

	public void setActeur(String acteur) {
		this.acteur = acteur;
	}

}
