package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionEvaluation generated by hbm2java
 */
@Entity
@Table(name = "question_evaluation", catalog = "management_resource_human_database")
public class QuestionEvaluation implements java.io.Serializable {

	private Integer idQuestion;
	private EvaluationExperience evaluationExperience;
	private String question;
	private String reponce;
	private String note;
	private Integer vote;

	public QuestionEvaluation() {
	}

	public QuestionEvaluation(EvaluationExperience evaluationExperience,
			String question, String reponce, String note, Integer vote) {
		this.evaluationExperience = evaluationExperience;
		this.question = question;
		this.reponce = reponce;
		this.note = note;
		this.vote = vote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_question", unique = true, nullable = false)
	public Integer getIdQuestion() {
		return this.idQuestion;
	}

	public void setIdQuestion(Integer idQuestion) {
		this.idQuestion = idQuestion;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_evaluation")
	public EvaluationExperience getEvaluationExperience() {
		return this.evaluationExperience;
	}

	public void setEvaluationExperience(
			EvaluationExperience evaluationExperience) {
		this.evaluationExperience = evaluationExperience;
	}

	@Column(name = "question", length = 500)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "reponce", length = 900)
	public String getReponce() {
		return this.reponce;
	}

	public void setReponce(String reponce) {
		this.reponce = reponce;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "vote")
	public Integer getVote() {
		return this.vote;
	}

	public void setVote(Integer vote) {
		this.vote = vote;
	}

}
