package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SheetInformation generated by hbm2java
 */
@Entity
@Table(name = "sheet_information", catalog = "management_resource_human_database")
public class SheetInformation implements java.io.Serializable {

	private Integer idFicheRenseignement;
	private CtpFolders ctpFolders;
	private String type;
	private Date dateStart;
	private Date dateEnd;
	private String post;
	private String business;
	private Integer remuneration;
	private Integer vote;
	private String diploma;
	private String specialty;
	private String establishment;
	private Integer years;
	private String note;
	private Boolean certificate;
	private String association;
	private String sector;
	private String question;
	private String reponce;

	public SheetInformation() {
	}

	public SheetInformation(CtpFolders ctpFolders, String type, Date dateStart,
			Date dateEnd, String post, String business, Integer remuneration,
			Integer vote, String diploma, String specialty,
			String establishment, Integer years, String note,
			Boolean certificate, String association, String sector,
			String question, String reponce) {
		this.ctpFolders = ctpFolders;
		this.type = type;
		this.dateStart = dateStart;
		this.dateEnd = dateEnd;
		this.post = post;
		this.business = business;
		this.remuneration = remuneration;
		this.vote = vote;
		this.diploma = diploma;
		this.specialty = specialty;
		this.establishment = establishment;
		this.years = years;
		this.note = note;
		this.certificate = certificate;
		this.association = association;
		this.sector = sector;
		this.question = question;
		this.reponce = reponce;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_fiche_renseignement", unique = true, nullable = false)
	public Integer getIdFicheRenseignement() {
		return this.idFicheRenseignement;
	}

	public void setIdFicheRenseignement(Integer idFicheRenseignement) {
		this.idFicheRenseignement = idFicheRenseignement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matricule")
	public CtpFolders getCtpFolders() {
		return this.ctpFolders;
	}

	public void setCtpFolders(CtpFolders ctpFolders) {
		this.ctpFolders = ctpFolders;
	}

	@Column(name = "type", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_start", length = 10)
	public Date getDateStart() {
		return this.dateStart;
	}

	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_end", length = 10)
	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	@Column(name = "post", length = 100)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "business", length = 100)
	public String getBusiness() {
		return this.business;
	}

	public void setBusiness(String business) {
		this.business = business;
	}

	@Column(name = "remuneration")
	public Integer getRemuneration() {
		return this.remuneration;
	}

	public void setRemuneration(Integer remuneration) {
		this.remuneration = remuneration;
	}

	@Column(name = "vote")
	public Integer getVote() {
		return this.vote;
	}

	public void setVote(Integer vote) {
		this.vote = vote;
	}

	@Column(name = "diploma", length = 100)
	public String getDiploma() {
		return this.diploma;
	}

	public void setDiploma(String diploma) {
		this.diploma = diploma;
	}

	@Column(name = "specialty", length = 100)
	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	@Column(name = "establishment", length = 100)
	public String getEstablishment() {
		return this.establishment;
	}

	public void setEstablishment(String establishment) {
		this.establishment = establishment;
	}

	@Column(name = "years")
	public Integer getYears() {
		return this.years;
	}

	public void setYears(Integer years) {
		this.years = years;
	}

	@Column(name = "note", length = 100)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "certificate")
	public Boolean getCertificate() {
		return this.certificate;
	}

	public void setCertificate(Boolean certificate) {
		this.certificate = certificate;
	}

	@Column(name = "association", length = 100)
	public String getAssociation() {
		return this.association;
	}

	public void setAssociation(String association) {
		this.association = association;
	}

	@Column(name = "sector", length = 100)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "question", length = 100)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "reponce", length = 100)
	public String getReponce() {
		return this.reponce;
	}

	public void setReponce(String reponce) {
		this.reponce = reponce;
	}

}
