package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StatesCandidates generated by hbm2java
 */
@Entity
@Table(name = "states_candidates", catalog = "management_resource_human_database")
public class StatesCandidates implements java.io.Serializable {

	private Integer idStatesCandidates;
	private CtpFolders ctpFolders;
	private String state;
	private String date;

	public StatesCandidates() {
	}

	public StatesCandidates(CtpFolders ctpFolders, String state, String date) {
		this.ctpFolders = ctpFolders;
		this.state = state;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_states_candidates", unique = true, nullable = false)
	public Integer getIdStatesCandidates() {
		return this.idStatesCandidates;
	}

	public void setIdStatesCandidates(Integer idStatesCandidates) {
		this.idStatesCandidates = idStatesCandidates;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matricule")
	public CtpFolders getCtpFolders() {
		return this.ctpFolders;
	}

	public void setCtpFolders(CtpFolders ctpFolders) {
		this.ctpFolders = ctpFolders;
	}

	@Column(name = "state", length = 1)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "date", length = 50)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
