package com.model;

// Generated 21 sept. 2016 11:14:47 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Validacs generated by hbm2java
 */
@Entity
@Table(name = "validacs", catalog = "management_resource_human_database")
public class Validacs implements java.io.Serializable {

	private Integer idValidac;
	private Set<ContenuValidac> contenuValidacs = new HashSet<ContenuValidac>(0);
	private Set<CtpFolders> ctpFolderses = new HashSet<CtpFolders>(0);

	public Validacs() {
	}

	public Validacs(Set<ContenuValidac> contenuValidacs,
			Set<CtpFolders> ctpFolderses) {
		this.contenuValidacs = contenuValidacs;
		this.ctpFolderses = ctpFolderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_validac", unique = true, nullable = false)
	public Integer getIdValidac() {
		return this.idValidac;
	}

	public void setIdValidac(Integer idValidac) {
		this.idValidac = idValidac;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "validacs")
	public Set<ContenuValidac> getContenuValidacs() {
		return this.contenuValidacs;
	}

	public void setContenuValidacs(Set<ContenuValidac> contenuValidacs) {
		this.contenuValidacs = contenuValidacs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "validacs")
	public Set<CtpFolders> getCtpFolderses() {
		return this.ctpFolderses;
	}

	public void setCtpFolderses(Set<CtpFolders> ctpFolderses) {
		this.ctpFolderses = ctpFolderses;
	}

}
